### ISSUE TITLE
Do we want transit data in the API?

### ISSUE THREAD

**Issue by mrandrewandrade** [uWaterloo/Datasets#123]
Do you know if we plan to add transit data?  According to http://campusdata.org/rankings/ we don't have it in our api.

My friend has made a transit app and has the GRT data, also would something like the feds bus schedule be helpful?

**Comment by jmccarth** [comment]
You may already be aware, but if not (and for others looking) the GTFS data for GRT is available through the [Region's Open Data Catalogue](http://www.regionofwaterloo.ca/en/regionalGovernment/OpenDataCatalogue.asp).

I don't know if the people behind the UW API want to rehost data that's already available or not, that's a question for them. It would be nice to have it available through an API rather than having to go to the Region to update data whenever they update it.

**Comment by nathanv** [comment]
closing this issue as per [this](https://github.com/uWaterloo/OpenData/issues/93#issuecomment-122294001) comment [OpenData/issues/93](https://github.com/uWaterloo/OpenData/issues/93)
